services:
  - type: web
    name: bepy
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: TYPESENSE_HOST
        value: ${TYPESENSE_HOST}
      - key: TYPESENSE_PORT
        value: ${TYPESENSE_PORT}
      - key: TYPESENSE_PROTOCOL
        value: ${TYPESENSE_PROTOCOL}
      - key: TYPESENSE_API_KEY
        value: ${TYPESENSE_API_KEY}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}